site_name: Umi Widgets
site_url: https://flbulgarelli.github.io/umi
nav:
  - Home: index.md
repo_url: "https://github.com/flbulgarelli/umi"
copyright: '© Copyright 2020 Franco Leonardo Bulgarelli '
theme: readthedocs
