site_name: Umi Tutoriales
site_url: https://flbulgarelli.github.io/umi
nav:
  - Home: index.md
  - Alineamientos: alignment.md
repo_url: "https://github.com/flbulgarelli/umi"
copyright: '© Copyright 2020 Franco Leonardo Bulgarelli & Ana Julia Velez Rueda'
theme: readthedocs
docs_dir: tutorials
extra_css:
  - css/tutorials.css
